In [1]:
import os
print(os.getcwd())

C:\Users\DELL

In [2]:
import os
print(os.getcwd())

C:\Users\DELL

In [2]:
import os
print(os.getcwd())

C:\Users\DELL\Naive_bayes

In [5]:
import pandas as pd

df = pd.read_csv(r"C:\Users\DELL\Downloads\gaussian_naive_bayes_loan_default.csv")

print(df.shape)
df.head()

(10000, 14)

,customer_id,age,annual_income,credit_score,loan_amount,loan_tenure_months,interest_rate,dti,utilization,days_past_due,inquiries_6m,existing_loans,employment_type,default
0,1,25,355158.0,612.0,312000.0,12,13.94,0.113,0.212,30,1,1,Self-employed,0
1,2,55,482630.0,681.0,455000.0,12,12.42,0.191,0.358,0,3,2,Salaried,0
2,3,50,754891.0,655.0,720000.0,24,12.21,0.360,0.376,0,2,1,Salaried,0
3,4,40,460078.0,749.0,813000.0,36,9.90,0.303,0.290,30,1,2,Self-employed,0
4,5,40,557728.0,751.0,562000.0,12,10.65,0.459,0.451,0,1,1,Contract,0

In [6]:
df.isnull().sum()

customer_id            0
age                    0
annual_income         90
credit_score          65
loan_amount            0
loan_tenure_months     0
interest_rate          0
dti                    0
utilization            0
days_past_due          0
inquiries_6m           0
existing_loans         0
employment_type        0
default                0
dtype: int64

In [7]:
df["default"].value_counts(normalize=True) * 100

default
0    80.57
1    19.43
Name: proportion, dtype: float64

In [8]:
df.describe()

,customer_id,age,annual_income,credit_score,loan_amount,loan_tenure_months,interest_rate,dti,utilization,days_past_due,inquiries_6m,existing_loans,default
count,10000.00000,10000.00000,9.910000e+03,9935.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,5000.50000,42.83710,7.568182e+05,687.762355,5.797487e+05,36.193200,12.224738,0.333885,0.426834,10.038000,2.00790,1.581500,0.194300
std,2886.89568,12.92583,4.572698e+05,77.859122,4.693482e+05,16.982612,1.948389,0.160759,0.209403,18.630573,1.42107,1.263138,0.395681
min,1.00000,21.00000,5.814600e+04,396.000000,2.300000e+04,12.000000,7.000000,0.020000,0.010000,0.000000,0.00000,0.000000,0.000000
25%,2500.75000,32.00000,4.498042e+05,635.000000,2.810000e+05,24.000000,10.927500,0.209000,0.263000,0.000000,1.00000,1.000000,0.000000
50%,5000.50000,43.00000,6.430130e+05,687.000000,4.510000e+05,36.000000,12.210000,0.320000,0.415000,0.000000,2.00000,1.000000,0.000000
75%,7500.25000,54.00000,9.380360e+05,740.000000,7.270000e+05,48.000000,13.540000,0.443000,0.582000,15.000000,3.00000,2.000000,0.000000
max,10000.00000,65.00000,6.375100e+06,900.000000,7.870000e+06,60.000000,19.330000,0.919000,0.971000,90.000000,9.00000,8.000000,1.000000

In [9]:
features = [
    "age",
    "annual_income",
    "credit_score",
    "loan_amount",
    "loan_tenure_months",
    "interest_rate",
    "dti",
    "utilization",
    "days_past_due",
    "inquiries_6m",
    "existing_loans"
]

X = df[features]
y = df["default"]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [11]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print(y_train.value_counts(normalize=True) * 100)
print(y_test.value_counts(normalize=True) * 100)

X_train: (8000, 11)
X_test: (2000, 11)
default
0    80.575
1    19.425
Name: proportion, dtype: float64
default
0    80.55
1    19.45
Name: proportion, dtype: float64

In [12]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_train = pd.DataFrame(
    imputer.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test = pd.DataFrame(
    imputer.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

In [13]:
print("Training missing values:")
print(X_train.isnull().sum())

print("\nTesting missing values:")
print(X_test.isnull().sum())

Training missing values:
age                   0
annual_income         0
credit_score          0
loan_amount           0
loan_tenure_months    0
interest_rate         0
dti                   0
utilization           0
days_past_due         0
inquiries_6m          0
existing_loans        0
dtype: int64

Testing missing values:
age                   0
annual_income         0
credit_score          0
loan_amount           0
loan_tenure_months    0
interest_rate         0
dti                   0
utilization           0
days_past_due         0
inquiries_6m          0
existing_loans        0
dtype: int64

In [14]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)

GaussianNB()

In [15]:
print("Class Priors:")
print(gnb.class_prior_)

print("\nFeature Means:")
print(
    pd.DataFrame(
        gnb.theta_,
        columns=X_train.columns,
        index=gnb.classes_
    )
)

Class Priors:
[0.80575 0.19425]

Feature Means:
         age  annual_income  credit_score    loan_amount  loan_tenure_months  \
0  42.867980  754182.960441    701.872479  583298.014272           36.295998
1  43.157658  770055.794723    629.929858  570173.745174           36.046332

   interest_rate       dti  utilization  days_past_due  inquiries_6m  \
0      11.943649  0.325378     0.420262       8.032113      1.973627
1      13.331956  0.370148     0.460283      18.175676      2.195624

   existing_loans
0        1.581291
1        1.582368

In [16]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_auc_score
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nROC-AUC:")
print(roc_auc_score(y_test, y_prob))

Confusion Matrix:

NameError: name 'y_pred' is not defined

In [18]:
y_pred = gnb.predict(X_test)

y_prob = gnb.predict_proba(X_test)[:, 1]

In [19]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_auc_score
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nROC-AUC:", roc_auc_score(y_test, y_prob))

Confusion Matrix:
[[1556   55]
 [ 315   74]]

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1611
           1       0.57      0.19      0.29       389

    accuracy                           0.81      2000
   macro avg       0.70      0.58      0.59      2000
weighted avg       0.78      0.81      0.78      2000


ROC-AUC: 0.7934764049856465

In [20]:
import numpy as np

y_pred_30 = (y_prob >= 0.30).astype(int)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_30))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_30))

Confusion Matrix:
[[1415  196]
 [ 221  168]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1611
           1       0.46      0.43      0.45       389

    accuracy                           0.79      2000
   macro avg       0.66      0.66      0.66      2000
weighted avg       0.79      0.79      0.79      2000

In [21]:
GaussianNB(var_smoothing=1e-9)

GaussianNB()

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV

pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("model", GaussianNB())
])

param_grid = {
    "model__var_smoothing": [
        1e-12,
        1e-10,
        1e-9,
        1e-7,
        1e-5,
        1e-3
    ]
}

grid = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=5,
    n_jobs=-1
)

In [23]:
X = df[features]
y = df["default"]

X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [24]:
grid.fit(X_train_raw, y_train)

print("Best parameters:", grid.best_params_)
print("Best CV ROC-AUC:", grid.best_score_)

Best parameters: {'model__var_smoothing': 1e-09}
Best CV ROC-AUC: 0.7869505038883606

In [25]:
best_model = grid.best_estimator_